# Blog info
blog_name: dahuang
slogan: learning makes me stronger
url: http://hrps.me

# Set avatar (Absolute url and relative url)
avatar: http://o6mo1i54c.bkt.clouddn.com/14943423484452.jpg?imageView2/2/w/200/h/200

# Set favicon
favicon: /favicon.ico

# For seo
keywords: javahuang,前端,java,python,css,JavaScript,docker,springboot,mongodb,oracle,mysql,vue,jquery

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
  - name: Project
    url: /project/
    target_blank: true #在新页面打开
  - name: Github
    url: https://github.com/javahuang
    target_blank: true


# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 友链
    url: /link/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  - name: RSS
    url: /atom.xml
    target_blank: true # 在新页面打开
  - name: 搜索
    url: /search/
    target_blank: false # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: 盒子

search_slogan:
  isShow: true # true|fase
  text: Can you find the bug of world ~

link_slogan:
  isShow: true # true|fase
  text: 交换友链可以邮件 javahrp@gmail.com


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: true
  btn_text: 支持一下
  tip: 扫一扫，支持dahuang
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: /images/wechatpay.png
    - type: 支付宝
      text: 支付宝扫一扫
      imgUrl: /images/alipay.png




post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
#personal_style: /css/personal-style.css

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: POST  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
baidu_analytics: ce8035f0c3530ebb28b00e8b913353a1

# Comment service
# disqus_shortname: javahuang
# hypercomments_id: 89821
# gentie_key: d16a7241e7cd4b389584ed8db2a4e8bc

# 注意，多说即将关闭，建议选用上面四个评论系统
# duoshuo_shortname: forsigner

gitment:
  client_id: d74bfd49f14fba220dba
  client_secret: 1b82b1520f36da3754a52713bd72f661c8c8e006
  repo: javahuang.github.io
  owner: javahuang

# 不算子,文章访问量统计和显示
busuanzi: true

# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "大黄，1990，Spring."
    - "擅长Java，对前端、Python也很有兴趣."
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@javahuang"
    text_value_url: https://github.com/javahuang
  - type: mail
    icon: icon-mail
    text_key: Gmail
    text_value: "javahuang@gmail.com"
  - type: location
    icon: icon-location
    text_value: 北京

link:
  - name: M-LOG
    info: 临渊羡鱼，不如退而结网
    url: http://mspring.org/
    avatar: http://mspring.org/static/blog/images/avatar.jpg


project:
  - type: personal
    name: fexo
    url: https://github.com/forsigner/fexo
    intro: A minimalist design theme for hexo